[2023-03-13 21:01:59] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [default] is not defined. at /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:212)
[stacktrace]
#0 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(137): Illuminate\\Log\\LogManager->resolve()
#1 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(124): Illuminate\\Log\\LogManager->get()
#2 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(664): Illuminate\\Log\\LogManager->driver()
#3 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Exceptions/Handler.php(274): Illuminate\\Log\\LogManager->error()
#4 /home/supra/private/gpt/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(46): Illuminate\\Foundation\\Exceptions\\Handler->report()
#5 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(454): NunoMaduro\\Collision\\Adapters\\Laravel\\ExceptionHandler->report()
#6 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(157): Illuminate\\Foundation\\Console\\Kernel->reportException()
#7 /home/supra/private/gpt/vendor/laravel-zero/framework/src/Kernel.php(96): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 /home/supra/private/gpt/gpt(35): LaravelZero\\Framework\\Kernel->handle()
#9 {main}
"} 
[2023-03-13 21:01:59] laravel.ERROR: Path cannot be empty {"exception":"[object] (ValueError(code: 0): Path cannot be empty at /home/supra/private/gpt/app/Commands/ConfigureCommand.php:35)
[stacktrace]
#0 /home/supra/private/gpt/app/Commands/ConfigureCommand.php(35): file_put_contents()
#1 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Commands\\ConfigureCommand->handle()
#2 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#6 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\\Container\\Container->call()
#7 /home/supra/private/gpt/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#8 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Console/Command.php(163): Symfony\\Component\\Console\\Command\\Command->run()
#9 /home/supra/private/gpt/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run()
#10 /home/supra/private/gpt/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#11 /home/supra/private/gpt/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#12 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#13 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#14 /home/supra/private/gpt/vendor/laravel-zero/framework/src/Kernel.php(96): Illuminate\\Foundation\\Console\\Kernel->handle()
#15 /home/supra/private/gpt/gpt(35): LaravelZero\\Framework\\Kernel->handle()
#16 {main}
"} 
[2023-03-13 21:02:02] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [default] is not defined. at /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:212)
[stacktrace]
#0 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(137): Illuminate\\Log\\LogManager->resolve()
#1 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(124): Illuminate\\Log\\LogManager->get()
#2 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(664): Illuminate\\Log\\LogManager->driver()
#3 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Exceptions/Handler.php(274): Illuminate\\Log\\LogManager->error()
#4 /home/supra/private/gpt/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(46): Illuminate\\Foundation\\Exceptions\\Handler->report()
#5 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(454): NunoMaduro\\Collision\\Adapters\\Laravel\\ExceptionHandler->report()
#6 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(157): Illuminate\\Foundation\\Console\\Kernel->reportException()
#7 /home/supra/private/gpt/vendor/laravel-zero/framework/src/Kernel.php(96): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 /home/supra/private/gpt/gpt(35): LaravelZero\\Framework\\Kernel->handle()
#9 {main}
"} 
[2023-03-13 21:02:02] laravel.ERROR: Path cannot be empty {"exception":"[object] (ValueError(code: 0): Path cannot be empty at /home/supra/private/gpt/app/Commands/ConfigureCommand.php:35)
[stacktrace]
#0 /home/supra/private/gpt/app/Commands/ConfigureCommand.php(35): file_put_contents()
#1 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Commands\\ConfigureCommand->handle()
#2 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#6 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\\Container\\Container->call()
#7 /home/supra/private/gpt/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#8 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Console/Command.php(163): Symfony\\Component\\Console\\Command\\Command->run()
#9 /home/supra/private/gpt/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run()
#10 /home/supra/private/gpt/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#11 /home/supra/private/gpt/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#12 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#13 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#14 /home/supra/private/gpt/vendor/laravel-zero/framework/src/Kernel.php(96): Illuminate\\Foundation\\Console\\Kernel->handle()
#15 /home/supra/private/gpt/gpt(35): LaravelZero\\Framework\\Kernel->handle()
#16 {main}
"} 
[2023-03-13 21:02:17] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [default] is not defined. at /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:212)
[stacktrace]
#0 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(137): Illuminate\\Log\\LogManager->resolve()
#1 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(124): Illuminate\\Log\\LogManager->get()
#2 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(664): Illuminate\\Log\\LogManager->driver()
#3 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Exceptions/Handler.php(274): Illuminate\\Log\\LogManager->error()
#4 /home/supra/private/gpt/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(46): Illuminate\\Foundation\\Exceptions\\Handler->report()
#5 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(454): NunoMaduro\\Collision\\Adapters\\Laravel\\ExceptionHandler->report()
#6 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(157): Illuminate\\Foundation\\Console\\Kernel->reportException()
#7 /home/supra/private/gpt/vendor/laravel-zero/framework/src/Kernel.php(96): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 /home/supra/private/gpt/gpt(35): LaravelZero\\Framework\\Kernel->handle()
#9 {main}
"} 
[2023-03-13 21:02:17] laravel.ERROR: Path cannot be empty {"exception":"[object] (ValueError(code: 0): Path cannot be empty at /home/supra/private/gpt/app/Commands/ConfigureCommand.php:35)
[stacktrace]
#0 /home/supra/private/gpt/app/Commands/ConfigureCommand.php(35): file_put_contents()
#1 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Commands\\ConfigureCommand->handle()
#2 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#6 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\\Container\\Container->call()
#7 /home/supra/private/gpt/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#8 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Console/Command.php(163): Symfony\\Component\\Console\\Command\\Command->run()
#9 /home/supra/private/gpt/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run()
#10 /home/supra/private/gpt/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#11 /home/supra/private/gpt/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#12 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#13 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#14 /home/supra/private/gpt/vendor/laravel-zero/framework/src/Kernel.php(96): Illuminate\\Foundation\\Console\\Kernel->handle()
#15 /home/supra/private/gpt/gpt(35): LaravelZero\\Framework\\Kernel->handle()
#16 {main}
"} 
[2023-03-13 21:06:30] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [default] is not defined. at /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:212)
[stacktrace]
#0 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(137): Illuminate\\Log\\LogManager->resolve()
#1 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(124): Illuminate\\Log\\LogManager->get()
#2 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(664): Illuminate\\Log\\LogManager->driver()
#3 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Exceptions/Handler.php(274): Illuminate\\Log\\LogManager->error()
#4 /home/supra/private/gpt/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(46): Illuminate\\Foundation\\Exceptions\\Handler->report()
#5 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(182): NunoMaduro\\Collision\\Adapters\\Laravel\\ExceptionHandler->report()
#6 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(250): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()
#7 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#8 {main}
"} 
[2023-03-13 21:06:30] laravel.ERROR: array_merge(): Argument #1 must be of type array, int given {"exception":"[object] (TypeError(code: 0): array_merge(): Argument #1 must be of type array, int given at /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:137)
[stacktrace]
#0 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(137): array_merge()
#1 /home/supra/private/gpt/app/Providers/ConfigServiceProvider.php(16): Illuminate\\Support\\ServiceProvider->mergeConfigFrom()
#2 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\ConfigServiceProvider->boot()
#3 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#7 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(1014): Illuminate\\Container\\Container->call()
#8 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(995): Illuminate\\Foundation\\Application->bootProvider()
#9 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#10 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(994): array_walk()
#11 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#12 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(269): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#13 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(383): Illuminate\\Foundation\\Application->bootstrapWith()
#14 /home/supra/private/gpt/vendor/laravel-zero/framework/src/Kernel.php(135): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#15 /home/supra/private/gpt/vendor/laravel-zero/framework/src/Kernel.php(107): LaravelZero\\Framework\\Kernel->bootstrap()
#16 /home/supra/private/gpt/vendor/laravel-zero/framework/src/Kernel.php(94): LaravelZero\\Framework\\Kernel->ensureDefaultCommand()
#17 /home/supra/private/gpt/gpt(35): LaravelZero\\Framework\\Kernel->handle()
#18 {main}
"} 
[2023-03-13 21:08:23] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [default] is not defined. at /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:212)
[stacktrace]
#0 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(137): Illuminate\\Log\\LogManager->resolve()
#1 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(124): Illuminate\\Log\\LogManager->get()
#2 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(664): Illuminate\\Log\\LogManager->driver()
#3 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Exceptions/Handler.php(274): Illuminate\\Log\\LogManager->error()
#4 /home/supra/private/gpt/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(46): Illuminate\\Foundation\\Exceptions\\Handler->report()
#5 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(182): NunoMaduro\\Collision\\Adapters\\Laravel\\ExceptionHandler->report()
#6 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(250): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()
#7 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#8 {main}
"} 
[2023-03-13 21:08:23] laravel.ERROR: file_get_contents(/home/supra/private/gpt/config.json): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_get_contents(/home/supra/private/gpt/config.json): Failed to open stream: No such file or directory at /home/supra/private/gpt/app/Providers/ConfigServiceProvider.php:17)
[stacktrace]
#0 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(250): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /home/supra/private/gpt/app/Providers/ConfigServiceProvider.php(17): file_get_contents()
#3 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\ConfigServiceProvider->boot()
#4 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#6 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#7 /home/supra/private/gpt/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#8 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(1014): Illuminate\\Container\\Container->call()
#9 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(995): Illuminate\\Foundation\\Application->bootProvider()
#10 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#11 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(994): array_walk()
#12 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#13 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(269): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#14 /home/supra/private/gpt/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(383): Illuminate\\Foundation\\Application->bootstrapWith()
#15 /home/supra/private/gpt/vendor/laravel-zero/framework/src/Kernel.php(135): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#16 /home/supra/private/gpt/vendor/laravel-zero/framework/src/Kernel.php(107): LaravelZero\\Framework\\Kernel->bootstrap()
#17 /home/supra/private/gpt/vendor/laravel-zero/framework/src/Kernel.php(94): LaravelZero\\Framework\\Kernel->ensureDefaultCommand()
#18 /home/supra/private/gpt/gpt(35): LaravelZero\\Framework\\Kernel->handle()
#19 {main}
"} 
